package com.personal.metricas.core.utils

object  Preferencias {

	val ACCESO_HERRAMIENTAS: String  ="ACCESO_HERRAMIENTAS"
	val CONFIGURACION_INICIAL: String  ="CONFIGURACION_INICIAL"
	val ACCESO_AJUSTES: String  ="ACCESO_AJUSTES"
	val ACCESO_SINCRONIZACION: String  ="ACCESO_SINCRONIZACION"
	val ENTORNO_PRO: String  ="ENTORNO_PRO"
	val SINCRONIZAR_AUTO: String  ="SINCRONIZAR_AUTO"
	val DIAS_CONSULTA_TRANSACCIONES: String  ="DIAS_CONSULTA_TRANSACCIONES"
}